### ISSUE TITLE
plano_properties.h

### ISSUE THREAD

**Issue by adamsepp** [crolando/plano#1] opened 2022-11-01 10:25 UTC
Hi, since I'm using the standard blueprint example up to now, I wanted to have a look at your implementation too.
But I'm not sure what else I need.
Seems like some file are missing? For example the "plano_properties.h" ?

**Comment by crolando** [comment] 2022-11-01 13:21
Hi, thanks for the report.  The problem is fixed in [#](https://github.com/crolando/plano/commit/e20ec39251149565886e7f4fc8633a9f0ca041de)

This was mistakenly added to the "nodos" repository, which is my testbed for the plano middleware.  

Nodo might be helpful to you when figuring out the API: it is an example showing how to define node types, register them and load/saving projects.  Thanks for trying it out! 

Note: there is a makefile floating around but it's out of date now.  use the VS project in nodos if you want to build it.

**Closed as completed by crolando** 2022-11-01 13:21 UTC

**Comment by adamsepp** [comment] 2022-11-12 08:37
Hi, sorry for the late reply...
Next week I will continuing testing...
Thank you very much! :-D

**Comment by adamsepp** [comment] 2023-01-19 18:40
Hi, currently I found more time to dig more into ImGui node editor...
Your approach with plano is very nice since I can easily register new types.
Also your description in nodos how to create a running project did work directly... :)

Perhaps I need to dig more into it, but I wanted to ask you about the following topic:

- Can I pass results from one node to the next one through the pin link?
- And is it possible to determine if a node is connected or not?
- I guess it is not ment to happen in "DrawAndEdit()" of the node right?

Reason: I need to build a system on which I follow the path of the connected nodes and work through them...

**Comment by adamsepp** [comment] 2023-01-19 18:53
Perhaps the normal approach is to pass the content to my actual application which interpretes this content then?
![image](https://user-images.githubusercontent.com/107212703/213534214-6d7c8d50-5684-4b4f-8777-03f98a61210d.png)

**Comment by crolando** [comment] 2023-01-19 20:23
Hi, I'm happy things are going well so far.  To answer concisely, these are features that I would like to add to nodos in the future, as it's an obviously critical part of the project.  Currently, I am working on project file save/load behaviors (which is stuffed into a branch in my casa project, but I plan on porting to nodos after the implementation is solid). 

For now, you will have to write those things.  It would be great if you did it in a fork of plano and nodos, or shared your code in your own project if possible.  

I want to point you to the plano file "src/handle_interactions.c".  around line 75, there is a statement like this:
```
                else if (isNodeAncestor(endNode,startNode)){
                    showLabel("x Connection would create a loop", ImColor(45, 32, 32, 180));
```

That "isNodeAncestor" function shows an example on how to do searches between nodes using the links.   

As far as I know, you should be able to include internal.h in your project.  Then when you create a context, that should expose the internals of "ContextData" in your main file.  From there, bob is your uncle.  You have access to s_Nodes and s_Links, and then can do all the graph analysis you need.

**Comment by crolando** [comment] 2023-01-20 01:55
I can queue these features after the file list/save feature is ready.  Your features are not designed, so the implementation will probably add api to Plano

**Comment by adamsepp** [comment] 2023-01-21 08:13
Hi, thank you for the info and quick reply!
I will most likely do a branch of your code and start to implement theese functions in another thread(s)...
(I used to programm RTO systems in C for the last 10 years and C++ only since the last year... So I'm still learning obout best object oriented architectures... Just that you know...)
I will update you here about the progress...

**Comment by adamsepp** [comment] 2023-01-21 08:24
ok, I created a fork of nodos and will try to work on it next week...
[nodos experimental](https://github.com/adamsepp/nodos_experimental)

**Comment by crolando** [comment] 2023-01-21 15:15
That's good to hear!  I wanted to prioritize writing in C specifically for outcomes like this.

**Comment by adamsepp** [comment] 2023-01-23 10:07
Hi, I pushed a trial version to [plano_experimental](https://github.com/adamsepp/plano_experimental)
and [nodo_experimental](https://github.com/adamsepp/nodos_experimental).
Current approach:
- attach object with own thread to each node... (instead of properties)
    -> Own thread, because I wanted to let them all work multithreaded... (later maybe from thread pool)
- added FlowWorker which wokes also in own thread
    -> The FlowWorker takes care about starting the node-functions (objects) accoring the link states...
    -> not ideal: currently it is searching permanently through all links and nodes
    -> problem: no mutex for "context" yet!
I wanted also to change the color of the nodes and links when they are done/running or so... But so far as I see, this is not possible unless I change also the imgui_node_editor stuff...

**Comment by crolando** [comment] 2023-02-04 17:18
Can you please raise a new open issue in this project, so we can track the "let's execute nodes" problem?  
Your implementation is pretty large and frankly, it's impressive you wrote so much in a little time.  I will need to dedicate a little time to read the code properly to honor your work.

**Comment by crolando** [comment] 2023-02-04 20:26
@adamsepp Please continue conversations in issue https://github.com/crolando/plano/issues/2
